[colors.primary]
	background = '0x121212'
	foreground = '0xf5f5f5'
[colors.cursor]
	text = '0xe0def4'
	cursor = '0xb4b4b4'
	
[colors.selection]
	text = "0xf5f5f5"
	background = "0xb4b4b4"

[colors.normal]
	black = '0xd5d5d5'
	red = '0x933737'
	green = '0xd87c4a'
	yellow = '0xbd4c4c'
	blue = '0x949494'
	magenta = '0xa7a7a7'
	cyan = '0xb4b4b4'
	white = '0xd5d5d5'

[colors.bright]
	black = '0x393552'
	red = '0xeb6f92'
	green = '0xa3be8c'
	yellow = '0xf6c177'
	blue = '0x569fba'
	magenta = '0xc4a7e7'
	cyan = '0x9ccfd8'
	white = '0xe0def4'
