# Colors (Ashen)

# Default Colors
[colors.primary]
background = '#121212'
foreground = '#f5f5f5'

# Selection Colors
[colors.cursor]
cursor = '#f5f5f5'
text = '#121212'

# Normal Colors
[colors.normal]
black = '#121212'
red = '#B14242'
green = '#D87C4A'
yellow = '#B14242'
blue = '#949494'
magenta = '#949494'
cyan = '#a7a7a7'
white = '#b4b4b4'

# Bright Colors
[colors.bright]
black = '#d5d5d5'
red = '#B14242'
green = '#D87C4A'
yellow = '#B14242'
blue = '#949494'
magenta = '#a7a7a7'
cyan = '#b4b4b4'
white = '#d5d5d5'
